<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSj7bnrk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSj7bnrk/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSj7bnrk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSj7bnrk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSj7bnrk\appProdProjectContainer([
    'container.build_hash' => 'Sj7bnrk',
    'container.build_id' => '579db689',
    'container.build_time' => 1594473294,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSj7bnrk');
